name: Fastify Application
# these are hook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Fastify Dependencies
        run: ./batect install-dep

      - name: Run testcase
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect int
