name: Fastify Application
# these are hook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Fastify Dependencies
        run: ./batect install-dep

      - name: Run testcase
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect lint

  deploy:
    needs: build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Login to heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build docker image and push to heroku registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a learn-fastify web

      - name: Run docker image on heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a learn-fastify web
